language: go

go:
  - 1.11.x
  - 1.10.x
  - 1.9.x
  - 1.8.x

notifications:
  email: false

before_install:
  - cp -r $GOROOT/src/cmd/internal $GOROOT/src/cmd/objfile
  - go get github.com/kr/pretty

script:
  - go build github.com/dearplain/goloader/examples/loader
  - go tool compile $GOPATH/src/github.com/dearplain/goloader/examples/base/base.go
  - ./loader -o base.o -run main.main
